flowchart TD
    n_11bde4ac_ba55_3b_start([Start])
    n_508ad35a7ed0dc26_Step_2["double"]
    n_11bde4ac_ba55_3b_end([Success])
    n_11bde4ac_ba55_3b_start --> n_508ad35a7ed0dc26_Step_2 --> n_11bde4ac_ba55_3b_end
