flowchart TD
    n_eb3bab03_a06d_38_start([Start])
    subgraph n_bb06303c671e8dfa["map_with_custom_serdes"]
    end
    subgraph n_854884afb82c9f52["map_with_custom_serdes-item-0"]
        n_f1a910c1de6193aa_Step_6["process_0"]
    end
    subgraph n_5a6489d72c7e1cb5["map_with_custom_serdes-item-2"]
        n_aadf1ef32ebcbc6f_Step_7["process_2"]
    end
    subgraph n_fcd4eddceb034fd3["map_with_custom_serdes-item-1"]
        n_e2fe10d2ffa3acc2_Step_8["process_1"]
    end
    n_eb3bab03_a06d_38_end([Success])
    n_eb3bab03_a06d_38_start --> n_bb06303c671e8dfa --> n_854884afb82c9f52 --> n_5a6489d72c7e1cb5 --> n_fcd4eddceb034fd3 --> n_eb3bab03_a06d_38_end
