flowchart TD
    n_a8e2ad52_e334_3a_start([Start])
    subgraph n_30850af7bf9484b0["map_operation"]
    end
    subgraph n_71b8c7102674e28a["map_operation-item-0"]
        n_1b4fb9f8c202c684_Step_5["map_item_0"]
    end
    subgraph n_8f4e2373cabbe052["map_operation-item-1"]
        n_3f744a147629986e_Step_6["map_item_1"]
    end
    subgraph n_47a91e323ebe6590["map_operation-item-2"]
        n_304b6a2541e4b69c_Step_11["map_item_2"]
    end
    subgraph n_9ad25a83b32a3d8f["map_operation-item-3"]
        n_19cbd2c80ea9b215_Step_12["map_item_3"]
    end
    subgraph n_2a984ba5ce8ed0f1["map_operation-item-4"]
        n_92f8ebff32714023_Step_16["map_item_4"]
    end
    n_a8e2ad52_e334_3a_end([Success])
    n_a8e2ad52_e334_3a_start --> n_30850af7bf9484b0 --> n_71b8c7102674e28a --> n_8f4e2373cabbe052 --> n_47a91e323ebe6590 --> n_9ad25a83b32a3d8f --> n_2a984ba5ce8ed0f1 --> n_a8e2ad52_e334_3a_end
